# Generated by Django 2.1.4 on 2019-01-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botresponse',
            name='name',
            field=models.CharField(default='Human', max_length=70),
        ),
    ]
